version: "3.7"
services: 
  back-end: 
    image: imallinson/project-back-end
    container_name: back-end
    ports: 
    - target: 8080
      published: 8080
      protocol: tcp
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  front-end: 
    image: imallinson/project-front-end
    container_name: front_end
    ports: 
    - target: 5000
      published: 80
      protocol: tcp
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  jenkins: 
    image: jenkins/jenkins
    container_name: jenkins
    ports: 
    - target: 8080
      published: 9000
      protocol: tcp
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
